WEBSOCKET_HOST = 'jukebox.local'
WEBSOCKET_URL = "ws://#{WEBSOCKET_HOST}:8081"
VOTE_URL = "http://#{WEBSOCKET_HOST}/external?"

DEFAULT_MENU_WIDTH=250.0

MENU_NOWPLAYING=111
MENU_CONSOLE_BUTT=222
MENU_PREFERENCES=333
MENU_CHECK_FOR_UPDATES=444
MENU_ABOUT=555
MENU_QUIT=666
MENU_SETTINGS=777
MENU_FORCE_REFRESH=888

TRACK_TITLE=1
TRACK_ARTIST=2
TRACK_ARTWORK_URL=3
TRACK_ALBUM=4

VOTE_VIEW_H=19
VOTE_VIEW_W=21

U_VOTE_BUTTON=32
D_VOTE_BUTTON=33
VOTE_TXT_VIEW=44

JB_MESSAGE_RECEIVED="JukeboxMessageReceived"
JB_UPDATED="JukeboxUpdated"
JB_DO_VOTE="JukeboxDoVote"
JB_TOGGLE_VOTE_SLIDER="ToggleVoteSlider"

SHOW_JB_DEFAULT="jb_console_visible"

CHOSEN_BY_TXT="Chosen by"