// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation VoteButton
@end

@implementation AlbumArtView
@end

@implementation NowplayingView
@end

@implementation ProgressView
@end

@implementation VoteButtonsView
@end

@implementation VoteMetricsView
@end

@implementation VoteView
@end

@implementation JukeboxControlWindow
@end

@implementation AppDelegate
@end

@implementation JukeboxControlController
@end

@implementation NowplayingController
@end

@implementation PreferencesController
@end

@implementation JukeboxHandler
@end

@implementation Notifier
@end

@implementation Persistence
@end

@implementation PlaylistHandler
@end

@implementation VoteHandler
@end

@implementation WebsocketConnector
@end

