// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <AudioToolbox/AudioToolbox.h>
#import <AudioUnit/AudioUnit.h>
#import <CFNetwork/CFNetwork.h>
#import <Carbon/Carbon.h>
#import <CoreAudio/CoreAudio.h>
#import <CoreData/CoreData.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>

@interface VoteButton: NSButton
-(IBAction) initWithVote:(id) vote;

@end

@interface AlbumArtView: NSImageView
-(IBAction) init;
-(IBAction) handle_vote_toggle_update;
-(IBAction) slidein_vote_view;
-(IBAction) slideout_vote_view;
-(IBAction) drawRect:(id) dirtyRect;
-(IBAction) mouseEntered:(id) event;
-(IBAction) updateTrackingAreas;
-(IBAction) make_turd;

@end

@interface NowplayingView: NSView
-(IBAction) initWithFrame:(id) frame;
-(IBAction) refresh:(id) jukebox;
-(IBAction) track;
-(IBAction) rating;
-(IBAction) time;
-(IBAction) draw_title_box;
-(IBAction) draw_artist_box;
-(IBAction) draw_album_box;
-(IBAction) draw_image_box;
-(IBAction) draw_addedby_box;
-(IBAction) update_title;
-(IBAction) update_artist;
-(IBAction) update_album;
-(IBAction) update_addedby;
-(IBAction) update_image;
-(IBAction) set_missing_artwork;
-(IBAction) update_votes;
-(IBAction) update_vote_txt;
-(IBAction) update_progress;

@end

@interface ProgressView: NSView
-(IBAction) init;
-(IBAction) tag;
-(IBAction) drawRect:(id) dirtyRect;
-(IBAction) increment_timer;
-(IBAction) progress_percent;
-(IBAction) progress;
-(IBAction) duration_to_seconds:(id) str;

@end

@interface UpcomingTableView: NSTableView
-(IBAction) init;

@end

@interface VoteButtonsView: NSView
-(IBAction) init;
-(IBAction) up_vote_button;
-(IBAction) down_vote_button;

@end

@interface VoteMetricsView: NSView
-(IBAction) init;
-(IBAction) tag;
-(IBAction) update_vote_txt;
-(IBAction) draw_vote_txt_holder;
-(IBAction) draw_vote_txt;
-(IBAction) draw_uvotes;
-(IBAction) draw_dvotes;
-(IBAction) no_vote_txt;

@end

@interface VoteView: NSView
-(IBAction) init;
-(IBAction) drawRect:(id) dirtyRect;
-(IBAction) draw_backing;

@end

@interface JukeboxControlWindow: NSWindow
-(IBAction) draggingEntered:(id) sender;
-(IBAction) draggingUpdated:(id) sender;
-(IBAction) performDragOperation:(id) sender;
-(IBAction) canBecomeKeyWindow;
-(IBAction) canBecomeMainWindow;
-(IBAction) register_vote:(id) button;
-(IBAction) build_views;

@end

@interface AppDelegate: NSObject <NSApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) build_status;
-(IBAction) build_preferences:(id) sender;
-(IBAction) update_status_bar_icon:(id) active;
-(IBAction) build_jukebox_controls;
-(IBAction) remove_jukebox_controls;
-(IBAction) hide_jukebox_controls;
-(IBAction) show_jukebox_controls;
-(IBAction) force_reconnect_to_websocket_server;
-(IBAction) register_defaults;
-(IBAction) build_jukebox;
-(IBAction) jukebox;
-(IBAction) connect_to_websocket_server;
-(IBAction) update_jukebox_controls_button_state:(id) state;
-(IBAction) handle_websocket_connection:(id) n;

@end

@interface JukeboxControlController: NSWindowController
-(IBAction) init;
-(IBAction) setup:(id) jukebox;
-(IBAction) windowDidBecomeMain:(id) notification;
-(IBAction) windowDidResignMain:(id) notification;
-(IBAction) choose_window_level;
-(IBAction) build_window;

@end

@interface NowplayingController: NSViewController
-(IBAction) init;
-(IBAction) build_view;

@end

@interface PreferencesController: NSWindowController

@property IBOutlet id u_vote_shortcut;
@property IBOutlet id d_vote_shortcut;

-(IBAction) init;
-(IBAction) awakeFromNib;
-(IBAction) toggle_always_show_votes:(id) button;

@end

@interface UpcomingController: NSViewController
-(IBAction) init;
-(IBAction) refresh:(id) jukebox;
-(IBAction) init_data;
-(IBAction) build_view;
-(IBAction) numberOfRowsInTableView:(id) table_view;
-(IBAction) refresh_tracks;
-(IBAction) current_track;

@end

@interface JukeboxHandler: NSObject
-(IBAction) initialize:(id) jukebox;
-(IBAction) after_update;
-(IBAction) do_notifications;

@end

@interface Notifier: NSObject
-(IBAction) initialize:(id) notifications;

@end

@interface Persistence: NSObject
@end

@interface PlaylistHandler: NSObject
-(IBAction) initialize:(id) track;
-(IBAction) add;
-(IBAction) alert_no_creds;
-(IBAction) do_notification;

@end

@interface VoteHandler: NSObject
-(IBAction) register;
-(IBAction) alert_no_creds;

@end

@interface WebsocketConnector: NSObject
-(IBAction) initialize;
-(IBAction) connect;
-(IBAction) reconnect;

@end

