// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <Carbon/Carbon.h>
#import <CoreServices/CoreServices.h>
#import <Security/Security.h>

@interface VoteButton: NSButton
-(IBAction) initWithVote:(id) vote;

@end

@interface AlbumArtView: NSImageView
-(IBAction) init;
-(IBAction) handle_vote_toggle_update;
-(IBAction) slidein_vote_view;
-(IBAction) slideout_vote_view;
-(IBAction) drawRect:(id) dirtyRect;
-(IBAction) mouseEntered:(id) event;
-(IBAction) updateTrackingAreas;
-(IBAction) make_turd;

@end

@interface NowplayingView: NSView
-(IBAction) initWithFrame:(id) frame;
-(IBAction) refresh:(id) jukebox;
-(IBAction) track;
-(IBAction) rating;
-(IBAction) draw_title_box;
-(IBAction) draw_artist_box;
-(IBAction) draw_album_box;
-(IBAction) draw_image_box;
-(IBAction) draw_addedby_box;
-(IBAction) update_title;
-(IBAction) update_artist;
-(IBAction) update_album;
-(IBAction) update_addedby;
-(IBAction) update_image;
-(IBAction) update_votes;
-(IBAction) show_vote_progress;

@end

@interface VoteButtonsView: NSView
-(IBAction) init;
-(IBAction) up_vote_button;
-(IBAction) down_vote_button;

@end

@interface VoteView: NSView
-(IBAction) init;
-(IBAction) drawRect:(id) dirtyRect;
-(IBAction) draw_backing;

@end

@interface JukeboxControlWindow: NSWindow
-(IBAction) canBecomeKeyWindow;
-(IBAction) canBecomeMainWindow;
-(IBAction) register_vote:(id) button;
-(IBAction) build_views;

@end

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) build_status;
-(IBAction) build_preferences:(id) sender;
-(IBAction) build_jukebox_controls:(id) sender;
-(IBAction) register_defaults;
-(IBAction) hide_jukebox_controls;
-(IBAction) build_jukebox;
-(IBAction) jukebox;
-(IBAction) connect_to_websocket_server;
-(IBAction) update_jukebox_controls_button_state:(id) state;

@end

@interface JukeboxControlController: NSWindowController
-(IBAction) init;
-(IBAction) setup:(id) jukebox;
-(IBAction) windowDidBecomeMain:(id) notification;
-(IBAction) windowDidResignMain:(id) notification;
-(IBAction) choose_window_level;
-(IBAction) build_window;

@end

@interface NowplayingController: NSViewController
-(IBAction) init;
-(IBAction) build_view;

@end

@interface PreferencesController: NSWindowController

@property IBOutlet id u_vote_shortcut;
@property IBOutlet id d_vote_shortcut;

-(IBAction) init;
-(IBAction) awakeFromNib;
-(IBAction) toggle_always_show_votes:(id) button;

@end

@interface JukeboxHandler: NSObject
-(IBAction) initialize:(id) jukebox;
-(IBAction) after_update;
-(IBAction) do_notifications;

@end

@interface Persistence: NSObject
@end

@interface VoteHandler: NSObject
-(IBAction) initialize:(id) vote;
-(IBAction) register;
-(IBAction) vote_url;
-(IBAction) username;
-(IBAction) password;
-(IBAction) alert_creds_wrong;
-(IBAction) alert_no_creds;

@end

@interface WebsocketConnector: NSObject
-(IBAction) initialize;
-(IBAction) connect;
-(IBAction) reconnect;

@end

